# Generated by Django 3.1.4 on 2021-01-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publishing_id',
            new_name='publishing',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='book_id',
            new_name='book',
        ),
    ]
