# Generated by Django 3.1.4 on 2021-01-31 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0005_auto_20210127_1829'),
    ]
    atomic = False

    operations = [
        migrations.RenameModel(
            old_name='Author_quote',
            new_name='Creator',
        ),
        migrations.AlterModelOptions(
            name='creator',
            options={'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
