# Generated by Django 3.1.4 on 2021-01-31 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0006_auto_20210131_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creator',
            options={},
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='author',
            new_name='creator',
        ),
    ]
