# Generated by Django 3.1.4 on 2021-01-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210104_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myperson',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
