# Generated by Django 3.1.4 on 2021-01-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.TimeField(auto_now=True),
        ),
    ]
